// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeIn4J6eSxl7S3YyeSpYWsOX1HAeFDOe4',
    appId: '1:524398845135:web:1312a9b022c0c211752bba',
    messagingSenderId: '524398845135',
    projectId: 'ecommerceapp-5c7a2',
    authDomain: 'ecommerceapp-5c7a2.firebaseapp.com',
    storageBucket: 'ecommerceapp-5c7a2.appspot.com',
    measurementId: 'G-F99F2K7Y7E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1utjjo7x95hUFOpfbcLztxgsjeWJ9QgM',
    appId: '1:524398845135:android:0f5d35480b3dcc88752bba',
    messagingSenderId: '524398845135',
    projectId: 'ecommerceapp-5c7a2',
    storageBucket: 'ecommerceapp-5c7a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDjoIC5Sfp7DASwPyfaLsd664aqMz2NWo',
    appId: '1:524398845135:ios:c9b6039adc380f91752bba',
    messagingSenderId: '524398845135',
    projectId: 'ecommerceapp-5c7a2',
    storageBucket: 'ecommerceapp-5c7a2.appspot.com',
    androidClientId: '524398845135-ekinhjq8kp2f7rdmum13mj38pl7skr8c.apps.googleusercontent.com',
    iosClientId: '524398845135-9kp2vnre6bp8km98e6skludo0o7u4t6k.apps.googleusercontent.com',
    iosBundleId: 'com.example.eShop',
  );
}
